site_name: UBC Wiki
site_author: CommunityUBC and contributors
site_description: |
  Tools, tips, and resources compiled by the UBC community on Reddit & Lemmy
repo_url: https://github.com/CommunityUBC/ubcwiki
repo_name: CommunityUBC/ubcwiki
site_url: https://communityubc.github.io/ubcwiki

plugins:
  - search
  - social
  - glightbox

extra_css:
  - stylesheets/extra.css
  
nav:
  - Home: 
    - Home: index.md
    - About Wiki Project: 
      - Technical Details: meta/project.md
      - Changelog: meta/changelog.md
    # - Outdated Setup & Config: meta/mdBook-config.md
    - Our online communities:
        - History of r/UBC & c/UBC: meta/community.md
        - Community Guidelines: meta/guidelines.md
        - Census Results:
          - 2017: meta/census/2017.md
          - 2018: meta/census/2018.md
    
  - Guides, Tools, Resources: 
    - â­ Helpful Tools: tools.md
    - Academics:
      - ğŸ“• Textbooks Guide: academics/classes/textbooks.md
      - ğŸ“œ Research Guide: academics/research.md
    - Wellbeing:
      - ğŸ§  Mental Health Resources: wellbeing/mental-health.md
  - Admissions & Housing: 
    - ğŸ“¬ Admissions Guide: admissions/guide.md
      # - BC Domestic: 
      # - International: 
      # - Transfer: 
    - ğŸ  Housing Guide: housing/guide.md
  - Course Planning:
    - ğŸ“… Registration Info & Tools: course-planning/registration.md
    - ğŸ¤« GPA Boosters & Recommended Courses: course-planning/recommended-courses.md
  
  - ğŸ“Œ Campus:
    - Places to Visit: campus/ubc-sights.md
    - Study Spots: campus/study-spots.md
    - Food Spots: campus/food.md
    - Lost & Found: campus/lost-and-found.md
    - ğŸ” Where to find...:
      - Lockers: campus/find/lockers.md
      - Printers: campus/find/printers.md
      - Showers: campus/find/showers.md
      - Nap / Sleep: campus/find/sleep.md
  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
  icon:
    repo: simple/github
  custom_dir: overrides

extra:
  social:
    - icon: simple/lemmy
      link: https://www.lemmy.ca/c/ubc
    - icon: simple/reddit
      link: https://www.reddit.com/r/ubc/
  generator: false