site_name: UBC Wiki
site_author: CommunityUBC and contributors
site_description: |
  This is the wiki project by CommunityUBC
repo_url: https://github.com/CommunityUBC/ubcwiki
repo_name: CommunityUBC/ubcwiki

plugins:
  - search
  # - social

extra_css:
  - stylesheets/extra.css
  
nav:
  - Home: index.md
  - About: 
    - About Wiki Project: meta/project.md
    - r/UBC and c/UBC: meta/community.md
    - Community Guidelines: meta/guidelines.md
    - Wiki Changelog: meta/changelog.md
    - Outdated Setup & Config: meta/mdBook-config.md
    - Census:
      - 2017: meta/census/2017.md
      - 2018: meta/census/2018.md
    
  - List of Tools & Websites: tools.md
  - ğŸ“¬ Admissions: admissions/guide.md
    # - BC Domestic: 
    # - International: 
    # - Transfer: 
  - ğŸ“… Course Planning:
    - Registration Info & Tools: course-planning/registration.md
    - GPA Boosters & Recommended Courses: course-planning/recommended-courses.md
  - ğŸ“• Academics:
    - Textbooks: academics/classes/textbooks.md
    - Research: academics/research.md
  - ğŸ“Œ Campus:
    - Places to Visit: campus/ubc-sights.md
    - Food Spots: campus/food.md
    - Study Spots: campus/study-spots.md
    - Lost & Found: campus/lost-and-found.md
    - ğŸ” Where to find...:
      - Lockers: campus/find/lockers.md
      - Printers: campus/find/printers.md
      - Showers: campus/find/showers.md
      - Nap / Sleep: campus/find/sleep.md
  - ğŸ“š General Guides:
    - Mental Health: general/mental-health.md
  - ğŸ  Housing:
    - Guide: housing/guide.md
  


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
  icon:
    repo: simple/github

extra:
  social:
    - icon: simple/lemmy
      link: https://www.lemmy.ca/c/ubc
    - icon: simple/reddit
      link: https://www.reddit.com/r/ubc/
  generator: false