site_name: UBC Wiki
site_author: CommunityUBC and contributors
site_description: |
  Tools, tips, and resources compiled by the UBC community on Reddit & Lemmy
repo_url: https://github.com/CommunityUBC/ubcwiki
repo_name: CommunityUBC/ubcwiki
site_url: https://ubcwiki.ca/

plugins:
  - search
  - privacy
  - git-revision-date-localized:
      type: custom
      custom_format: "Last updated: %B %d, %Y"
      fallback_to_build_date: true
      exclude:
        - index.md
  - social:
      cards_layout_options:
        font_family: Noto Sans
      enabled: !ENV [CI, false]
  - glightbox
  - redirects:
      redirect_maps:
        # 'index.html': 'index.md' # DO NOT do this, death loop
        'meta/guidelines.html': 'meta/guidelines.md'
        'tools.html': 'tools.md'
        'general/mental-health.html': 'wellbeing/mental-health.md'
        'campus/ubc-sights.html': 'campus/ubc-sights.md'
        'academics/classes/textbooks.html': 'academics/classes/textbooks.md'

extra_css:
  - stylesheets/extra.css
  
nav:
  - UBC Wiki: 
    - Home: index.md
    - About Wiki Project: 
      - Installation Guide: meta/project.md
      - Old Setup Guide: meta/mdBook-config.md
      - Changelog: meta/changelog.md
    # - Outdated Setup & Config: meta/mdBook-config.md
    - Our online communities:
        - History & Best Posts: meta/community.md
        - Community Guidelines: meta/guidelines.md
        - Census Results:
          - 2017: meta/census/2017.md
          - 2018: meta/census/2018.md
    
  - âœ¨ Essential Tools & Guides: 
    - â­ Helpful Tools: tools.md
    - ğŸ“¬ Admissions Guide: admissions/guide.md
      # - BC Domestic: 
      # - International: 
      # - Transfer: 
    - ğŸ  Housing Guide: housing/guide.md
    - ğŸ“… Course Registraion & Tools: course-planning/registration.md
    - Academic Support:
      - ğŸ“• Textbooks Guide: academics/classes/textbooks.md
      - ğŸ“œ Research Guide: academics/research.md
      - ğŸ¤« GPA Boosters & Recommended Courses: course-planning/recommended-courses.md
    - Student Wellbeing:
      - ğŸ§  Mental Health Resources: wellbeing/mental-health.md    
  
  - ğŸ“Œ Get around Campus:
    - General Guide: campus/general.md 
    - Places to Visit: campus/ubc-sights.md
    - Study Spots: campus/study-spots.md
    - Food Spots: campus/food.md
    - Lost & Found: campus/lost-and-found.md
    - ğŸ” Where to find...:
      - Lockers: campus/find/lockers.md
      - Printers: campus/find/printers.md
      - Showers: campus/find/showers.md
      - Sleep-spots: campus/find/sleep.md
  

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
  icon:
    logo: material/bookshelf
    repo: simple/github
  favicon: assets/bookshelf.svg
  custom_dir: overrides

extra:
  generator: false

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js