site_name: UBC Wiki
site_author: CommunityUBC and contributors
site_description: |
  Tools, tips, and resources compiled by the UBC community on Reddit & Lemmy
repo_url: https://github.com/CommunityUBC/ubcwiki
repo_name: CommunityUBC/ubcwiki
site_url: https://ubcwiki.ca/

extra_css:
  - stylesheets/extra.css
  
nav:
  - UBC Wiki: 
    - Home: index.md
    - Our online communities:
        - History & Best Posts: meta/community.md
        - Community Guidelines: meta/guidelines.md
        - Census Results:
          - 2018: meta/census/2018.md
          - 2017: meta/census/2017.md
    - Technical Details: 
      - Installation Guide: meta/project.md
      - Old Setup Guide: meta/mdBook-config.md
      - Changelog: meta/changelog.md
    # - Outdated Setup & Config: meta/mdBook-config.md
    
    
  - âœ¨ Essential Tools & Guides: 
    - â­ Helpful Tools: tools.md
    - ğŸ“¬ Admissions Guide: admissions/guide.md
      # - BC Domestic: 
      # - International: 
      # - Transfer: 
    - ğŸ  Housing Guide: housing/guide.md
    - ğŸ“… Course Registraion & Tools: course-planning/registration.md
    - Academic Support:
      - ğŸ“• Textbooks Guide: academics/classes/textbooks.md
      - ğŸ“œ Research Guide: academics/research.md
      - ğŸ¤« GPA Boosters & Recommended Courses: course-planning/recommended-courses.md
    - Student Wellbeing:
      - ğŸ§  Mental Health Resources: wellbeing/mental-health.md    
  
  - ğŸ“Œ Get around Campus:
    - General Guide: campus/general-guide.md 
    - Places to Visit: campus/ubc-sights.md
    
    
    - Lost & Found: campus/lost-and-found.md
    - Locations:
      - ğŸ“– Study spots: campus/study-spots.md
      - ğŸ´ Food spots: campus/food.md
    - Amenities:
      - ğŸ›… Lockers: campus/lockers.md
      - ğŸ¿ Microwaves: campus/microwaves.md
      - ğŸ›ï¸ Naps / Sleeping: campus/sleep.md
      - ğŸ–¨ï¸ Printers/Scanners/etc.: campus/printers.md
      - ğŸš¿ Showers: campus/showers.md
      - ğŸš° Water Fountains: campus/water-fountains.md
      

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
  icon:
    logo: material/bookshelf
    repo: simple/github
  favicon: assets/bookshelf.svg
  custom_dir: overrides

extra:
  generator: false

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - search
  - privacy
  - git-revision-date-localized:
      type: custom
      custom_format: "Last updated: %B %d, %Y"
      fallback_to_build_date: false
      exclude:
        - index.md
  - social:
      cards_layout_options:
        font_family: Noto Sans
      enabled: !ENV [CI, false]
  - glightbox
  - redirects:
      redirect_maps:
        # 'index.html': 'index.md' # DO NOT do this, causes death loop

        # migration from mdbook
        'meta/guidelines.html': 'meta/guidelines.md'
        'tools.html': 'tools.md'
        'general/mental-health.html': 'wellbeing/mental-health.md'
        'campus/ubc-sights.html': 'campus/ubc-sights.md'
        'academics/classes/textbooks.html': 'academics/classes/textbooks.md'

        # pages that were moved from original location
        'campus/general.md': 'campus/general-guide.md'
        'campus/find/lockers.md': 'campus/lockers.md'
        'campus/find/printers.md': 'campus/printers.md'
        'campus/find/showers.md': 'campus/showers.md'
        'campus/find/sleep.md': 'campus/sleep.md'

        # Memorable 'find' links
        'find/study-spots.md': 'campus/study-spots.md'
        'find/study.md': 'campus/study-spots.md'
        'find/food.md': 'campus/food.md'
        'find/food-spots.md': 'campus/food.md'
        'find/food-places.md': 'campus/food.md'
        'find/lockers.md': 'campus/lockers.md'
        'find/lockers.md': 'campus/lockers.md'
        'find/microwaves.md': 'campus/microwaves.md'
        'find/microwave.md': 'campus/microwaves.md'
        'find/nap.md': 'campus/sleep.md'
        'find/naps.md': 'campus/sleep.md'
        'find/nap-spots.md': 'campus/sleep.md'
        'find/napping-spots.md': 'campus/sleep.md'
        'find/napping-places.md': 'campus/sleep.md'
        'find/sleep.md': 'campus/sleep.md'
        'find/sleep-spots.md': 'campus/sleep.md'
        'find/printer.md': 'campus/printers.md'
        'find/printers.md': 'campus/printers.md'
        'find/scanners.md': 'campus/printers.md'
        'find/water.md': 'campus/water-fountains.md'
        'find/fountain.md': 'campus/water-fountains.md'
        'find/water-fountain.md': 'campus/water-fountains.md'
        'find/water-fountains.md': 'campus/water-fountains.md'
